version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - mysql
      - ai-python
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mysql://root:password@mysql/healthwise_db  # Example environment variable

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: healthwise_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  ai-python:
    image: python:3.8-slim
    volumes:
      - ./backend/scripts:/scripts
    working_dir: /scripts
    command: python chatbot_service.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Example of passing an API key from .env file

volumes:
  mongo_data:
  mysql_data:

networks:
  default:
    driver: bridge
